### ISSUE TITLE
Layout, CSS, JS error

### ISSUE THREAD

**Issue by procontentxyz** [jonas-hoebenreich/wc-donation-platform#10]
I have storefront theme installed

1. when donation form popup opens, there are no background colors on checkout steps titles.

2. neither those three loading indicator are showing when go to another step after clicking next.

2. when click on country select countries list is not showing up.

please see here: https://lockunlock.me/opg/how-to-earn-the-easy-way/

click on unlock button to open donation pop up form.

please help with the issue.

3. How can i pass addtional hidden custom meta in donation checkout form, and show on thank you page after that.

**Comment by jonas-hoebenreich** [comment]
Thanks for bringing this bug to my attention. I will work on an update in the next few days.
