### ISSUE TITLE
getting js error, when i am logged out

### ISSUE THREAD

**Issue by procontentxyz** [jonas-hoebenreich/wc-donation-platform#12]
Uncaught TypeError: Cannot read properties of undefined (reading 'checkValidity')
    at HTMLDocument.<anonymous> (wcdp.min.js:1:2514)   <<<<<<<<<<<<<<<<<<<<<<<<-----------------------------
    at e (jquery.min.js?ver=3.6.0:2:30038)
    at t (jquery.min.js?ver=3.6.0:2:30340)

getting above error while i am logged out on my site & try to open donation form pop up.

when i am logged in, its working fine.

error page:  https://lockunlock.me/twtr/dheeth/?NjBVWWpkdUg2ZG1kOGo5dG9vOEJZVGdqQ1NOWVZzbStDOFVDRCtNQU93elVnT1lJYUlHZktqYmwvcnpaSFhWRg==

**Comment by jonas-hoebenreich** [comment]
![image](https://user-images.githubusercontent.com/64426524/151118833-a8b51717-5aef-44b2-b880-a8f64bdcf325.png)
You have disabled donations for logged out users. Please enable guest checkout.
Nevertheless, the error should not occur and the appropriate notice should be displayed instead. I'll put it on the todo list for the next release.
