### ISSUE TITLE
How to create donation project automatically after user register?

### ISSUE THREAD

**Issue by procontentxyz** [jonas-hoebenreich/wc-donation-platform#14]
i noticed: If we create product using code, Donation dont get active,

when we hit publish manually, donation become active.

please guide for below issue:

1. Why we have to publish product manually to make product donation active, If product is already published using code.

**Comment by jonas-hoebenreich** [comment]
Hi,
The problem is probably that you are not adding the product appropriately for WooCommerce:
https://wordpress.stackexchange.com/questions/137501/how-to-add-product-in-woocommerce-with-php-code

**Comment by procontentxyz** [comment]
Could please whats wrong with above code OR whats missing.

Because everthing is working right, only product donation become active after hitting publish button manually not with programmatically publish.

**Comment by jonas-hoebenreich** [comment]
While a product is a custom post type, WooCommerce adds some additional logic using the wc_product_meta_lookup table, such as the product price, whether the product is available, etc. This additional metadata is set as soon as someone manually updates the product.
For example, your code is still missing a price:
`update_post_meta( $post_id, '_price', '1' );`
I think your link is from a time when the wc_product_meta_lookup table did not exist.

The Donation Platform for WooCommerce specific code looks pretty good to me.

**Comment by jonas-hoebenreich** [comment]
Also, I would be grateful if you could post support-related questions in the WordPress support forum in the future: https://wordpress.org/support/plugin/wc-donation-platform/
This will make the questions easier to find for other users.

**Comment by procontentxyz** [comment]
ok brother, actually i got faster response here 💯 

but if you are saying, i will do what you told me to do brother ...


not problem...


btw doing this:
update_post_meta( $post_id, '_price', '1' );

will solve my problem??

i have not yet tested?

**Comment by jonas-hoebenreich** [comment]
```
$product = new WC_Product_Simple();

$product->set_name( 'Post Title' );
$product->set_slug( 'slug' );
$product->set_status( "publish" );

$product->set_virtual( "yes" );
$product->set_regular_price( "1" ); //must
$product->set_catalog_visibility( "visible" ); //must
$product->set_description( "" ); // (optional)
$product->set_short_description( "" ); // (optional)

$product->update_meta_data("_donable", "yes");

$product->update_meta_data("wcdp-settings[0]", "1");
$product->update_meta_data("wcdp-settings[1]", "[100,200,500,1000]");

$product->save();
```
When I run this code with code snippets, it works flawlessly.
What exactly is not working for you?

**Comment by procontentxyz** [comment]
$product->update_meta_data("_donable", "yes");


This is not working, i have to manually set product as donable by checkbox

**Comment by jonas-hoebenreich** [comment]
That is weird, when I open the product page in the frontend, everything works fine
Where is the `set_donable()` function defined?

**Comment by procontentxyz** [comment]
could you please check on your end:

1. Open auto created product & check if donation product checkbox is CHECKED or not ?


i thought like $product->set_virtual( "yes" );


$product->set_donable( "yes" ); will work.... 🗡️ 

so silly of me.... hehehe

**Comment by jonas-hoebenreich** [comment]
yes it is

**Comment by procontentxyz** [comment]
i am confused what happened on my side....  

:(
