### ISSUE TITLE
Error report

### ISSUE THREAD

**Issue by procontentxyz** [jonas-hoebenreich/wc-donation-platform#16]
I noticed few things about your plugin

Donation got deactivated for product in two cases:

1. if i copy existing product to draft

https://youtu.be/kDduUjamLOk

2. If i update product data from quick edit button in admin

https://youtu.be/mGiWTBvuNB0

Please fix these issues.

**Comment by jonas-hoebenreich** [comment]
Hi, thanks for the report. I think I found out why it doesn't work. Let's see if I can find a fix. By the way, the affected function is wcdp_save_post_product, if you want to join the bug fixing.
