### ISSUE TITLE
Remove ajax it takes time

### ISSUE THREAD

**Issue by procontentxyz** [jonas-hoebenreich/wc-donation-platform#17]
Is there any way to remove ajax update price on select preset price options

I takes time, also newbie or non techy customer would click Donate now button before it get updated with new price option through ajax.

It would be better if on click price preset option, page reload with updated price @ checkout page.

**Comment by jonas-hoebenreich** [comment]
Hi, I'm not quite sure which AJAX call you are referring to. In general, Donation Platform for WooCommerce only executes an AJAX call when necessary. However, other payment gateways (e.g. Stripe or PayPal) use significantly more AJAX calls.
In general, by the way, an AJAX call is more resource-efficient than a completely new page load.
