### ISSUE TITLE
Thank You Page - User Flow

### ISSUE THREAD

**Issue by mcworks** [jonas-hoebenreich/wc-donation-platform#21]
Following the same great user experience and flow provided with the plugin, steps 1, 2, 3..   

How can we have the thank you page follow in the same sequence (be step4 or silent) as opposed to opening a totally new page and disrupting the user flow experience. This is especially key also for the pop-up scenario, so that at the end of the process it is the user who closes the popup and the initial main page is maintained.

**Comment by jonas-hoebenreich** [comment]
Under this link you will find some info on how to optimize and customize the Thank You page: https://wcdp.jonh.eu/documentation/advanced/custom-thank-you-page/
Adding the thank you page to the individual steps is currently not possible out of the box, but I would appreciate your support in the form of a pull request.
An improved thank you page is actually already on my roadmap: https://wcdp.jonh.eu/documentation/support/roadmap/

**Comment by jonas-hoebenreich** [comment]
Hi, thanks for your feedback. I had already understood you correctly, but obviously expressed myself unclearly. For me, anything that changes the nature of the thank you page is a custom thank you page.
However, your request to integrate the thank you page into the popup is relatively complex to implement. I like the idea though and will keep it in mind when making improvements to the checkout.

**Comment by mcworks** [comment]
Thanks for the consideration..
Also, I have not seen documentation on how you customized/removed some of the checkout fields - kind.y advise.

**Comment by jonas-hoebenreich** [comment]
You can find the article under the following link: https://wcdp.jonh.eu/documentation/integrations/custom-form-fields/

**Comment by mcworks** [comment]
Thanks
