### ISSUE TITLE
Translating the plugin

### ISSUE THREAD

**Issue by Buyback1** [jonas-hoebenreich/wc-donation-platform#22]
Hey there,

First of all I would like to thank you for the great work. I'm currently creating a website for a local NGO and I am using your plug-in for donations. I need to translate the plugin and I am working with Loco Translate yet the strings translations do not appear on the website. I have to admit that I am not sure that I am doing it the right way so I thought I might just ask away :)). Is it possible to translate the plugin with LocoTranslate, if so are there any other steps I have to take in order to translate it?

Thank you again for your work and looking forward to hearing from you.

Cheers,
Peter

**Comment by jonas-hoebenreich** [comment]
Hi Peter,
thanks for reaching out.
The translation with Loco translate should work normally. Only the strings for "Your Contribution" & "Choose an amount" are set via the donation settings. Which strings are affected in your case?
Best,
Jonas

**Comment by Buyback1** [comment]
Hey Jonas,

Thank you so much for the reply.

[image: image.png]

I've translate about 8 percent of the plug-in, mainly for the buttons and
texts that appear throughout the checkout process. It says something here
about the bundle not being fully configured, yet I don't know what I am
doing wrong.

[image: image.png]
[image: image.png]

I've attached 2 printscreens, I don't know if it helps. Thank you so much
for your help.

Regards,
Peter

**Comment by jonas-hoebenreich** [comment]
Hi Peter,
the images you pasted are not displaying properly for me. Could you please add them again via the GitHub web portal? Also, I suspect that your problem is a wrong setting of Loco Translate: https://localise.biz/wordpress/plugin/faqs
Would you perhaps be interested in making the translation available to everyone? https://translate.wordpress.org/projects/wp-plugins/wc-donation-platform/
Best, Jonas

**Comment by Buyback1** [comment]
Hi Jonas,

Sorry for the late reply I just noticed the notification email went in the wrong folder.

![image](https://user-images.githubusercontent.com/110970337/185382601-f0cd0786-2561-4e16-9832-dcd506d612a7.png)

![image (1)](https://user-images.githubusercontent.com/110970337/185382596-0badf69e-14ef-4665-aee0-99aab9007809.png)

I reattached the images here. As for making the translation available for everyone, I'd be more than glad.

Thank you the link for setting up Loco Translate, I'll check that one too.

Cheers,
Peter

**Comment by jonas-hoebenreich** [comment]
Here is the configuration that works for me:
[loco.zip](https://github.com/jonas-hoebenreich/wc-donation-platform/files/9384048/loco.zip) (extract file and then import xml file in Loco translate)
When translating there is a button "Sync", did you click this? Also, I recommend you to store the translations in a custom folder to prevent overwriting when the plugin is updated.

Hope this helps :)

**Comment by abdulloh10** [comment]
> Hi Peter, thanks for reaching out. The translation with Loco translate should work normally. Only the strings for "Your Contribution" & "Choose an amount" are set via the donation settings. Which strings are affected in your case? Best, Jonas

Hello Jonas,

I used loco translate, but it didn't work in the body of the notification email message.

Thank you so much
for your help.

Regards,
Fahmi

**Comment by jonas-hoebenreich** [comment]
Hi Fahmi,

the email strings can be set in the WooCommcerce settings for emails.

Regards,
Jonas

**Comment by abdulloh10** [comment]
> Hi Fahmi,
> 
> the email strings can be set in the WooCommcerce settings for emails.
> 
> Regards, Jonas

When my wordpress uses Indonesian, in the email when the order status is Completed the word Donation is still Donation, said
Donor details remain Donor details but in views other than email change according to translation.

When my wordpess uses English USA, the sentences in the contents of the email have been successfully translated as desired..

Owhya in /my-account/edit-address/ the word donation also failed to translate, it's still donation.

Regards,
Fahmi

**Comment by jonas-hoebenreich** [comment]
Can you send me a complete list of the affected strings?
Could you please also upload the strings you translated on the WordPress translation page (https://translate.wordpress.org/projects/wp-plugins/wc-donation-platform/)? Then I can install the language locally and understand the error.

Regards,
Jonas

**Comment by jonas-hoebenreich** [comment]
I just fixed the textdomain in 3 strings
https://github.com/jonas-hoebenreich/wc-donation-platform/commit/00224da926efb3aee34bbc631a2be5e78eb34c6a
