### ISSUE TITLE
Is there a way i can change the "Order"  in admin as "Donation" and apply same elsewhere in emails, analytics & reports

### ISSUE THREAD

**Issue by mgkmoha** [jonas-hoebenreich/wc-donation-platform#23]
My requirement is to provide more personalized and customized experience.
 
Is there a way to change the "Order" in admin as "Donation" and apply the same elsewhere specially in emails, analytics, reports and elsewhere.

I did check in plugin documentation and in WooCommerce filters and hook but could not find.

**Comment by jonas-hoebenreich** [comment]
Hi mgkmoha,
thanks for reaching out.
Donation Platform for WooCommerce currently focuses on end user facing front end changes. You can use Loco Translate or take a deep dive into WooCommerce development here: https://github.com/woocommerce/woocommerce/tree/trunk/plugins/woocommerce/includes/admin
Regards,
Jonas
