### ISSUE TITLE
Feature request! #2

### ISSUE THREAD

**Issue by KaloyanDDimitrov** [jonas-hoebenreich/wc-donation-platform#26]
Hello is there an option to add a different Thank You Certificate for different range of donation? For example from 3$-50$ Silver certificate, 50-100$ golden and etc.

**Comment by jonas-hoebenreich** [comment]
Hi KaloyanDDimitrov,
thanks for reaching out.
I've [added a new filter](https://github.com/jonas-hoebenreich/wc-donation-platform/pull/27/commits/508701176764aaed85ad24a23f2a35e85694e13f) called `wcdp_certificate_background_image` that allows you to alter the background image.
Using the code snippet below and and a plugin like [Code Snippets](https://wordpress.org/plugins/code-snippets/) you can implement the background image logic yourself.

Best regards
Jonas

```
add_filter('wcdp_certificate_background_image', function($link, $order_id, $total) {
	if ($total < 50) {
		return 'https://yoursite.com/background1.jpg';
	}
	return 'https://yoursite.com/background2.jpg';
}, 10, 3);
```
