### ISSUE TITLE
Woocommerce update required

### ISSUE THREAD

**Issue by incmak** [jonas-hoebenreich/wc-donation-platform#32]
**Describe the bug**
I installed the plugin v.1.2.9 on my wordpress site having woocommerce version 7.3.0 displayed the following error: Donation Platform for WooCommerce is inactive. This version of Donation Platform for WooCommerce requires WooCommerce 4.0.0 or newer. Please update WooCommerce.

**To Reproduce**
1. Go to 'wordpress plugin install'
2. Click on install wc-donation-plaform.'
3. See error on top

**Expected behavior**
It shouldn't throw this error because i am already on woocommerce v4 above

**Error Log**
Please list error messages (e.g. in the PHP error log or in the frontend).

**Screenshots**

**Device (please complete the following information):**
 - Device: [laoptop]
 - OS: [e.g.windows]
 - Browser [chrome]
 - Version 1.2.9

**Additional context**

**WordPress Environment**
Under WooCommerce -> Status -> Get system report you can generate a system report. Please insert it here.
`
### WordPress Environment ###

WordPress address (URL): http://vmssh.com
Site address (URL): http://vmssh.com
WC Version: 7.3.0
REST API Version: ✔ 7.3.0
WC Blocks Version: ✔ 9.1.5
Action Scheduler Version: ✔ 3.4.0
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 2 GB
WP Debug Mode: –
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: LiteSpeed
PHP Version: 7.4.33
PHP Post Max Size: 2 GB
PHP Time Limit: 120
PHP Max Input Vars: 5000
cURL Version: 7.71.0
OpenSSL/1.1.1p

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.5.17-MariaDB-cll-lve
Max Upload Size: 2 GB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Post Type Counts ###

apus_brand: 8
apus_footer: 5
apus_testimonial: 6
attachment: 163
custom_css: 1
customize_changeset: 1
give_forms: 13
give_payment: 195
give_volunteer: 10
mc4wp-form: 1
nav_menu_item: 46
page: 29
post: 14
product: 1
revision: 159
simple_event: 6
wp_global_styles: 1
wpcf7_contact_form: 4

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (17) ###

Hostinger: by Hostinger – 1.0.1
All-in-One WP Migration: by ServMask – 7.68
Apus Charityheart: by ApusTheme – 1.0.0
Apus Framework: by Team ApusTheme – 2.1
Apus Simple Event: by ApusTheme – 1.0.0
CMB2: by CMB2 team – 2.10.1
Contact Form 7: by Takayuki Miyoshi – 5.7.3
Give - Donation Plugin: by GiveWP – 2.23.2
WPBakery Page Builder: by Michael M - WPBakery.com – 6.1
LiteSpeed Cache: by LiteSpeed Technologies – 5.3.2
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.0
Razorpay Payment Button for Visual Composer: by Razorpay – 1.0.2
Razorpay Payment Button: by Razorpay – 2.4.5
Slider Revolution: by ThemePunch – 6.2.2
Donation Platform for WooCommerce: Fundraising & Donation Management: by Jonas Höbenreich – 1.2.6
WooCommerce: by Automattic – 7.3.0
WPForms Lite: by WPForms – 1.7.9.1

### Inactive Plugins (3) ###

Akismet Anti-Spam: by Automattic – 5.0.2
Hello Dolly: by Matt Mullenweg – 1.7.2
Razorpay Payment Button for Elementor: by Razorpay – 1.2.5

### Settings ###

API Enabled: ✔
Force SSL: –
Currency: INR (₹)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
Order datastore: WC_Order_Data_Store_CPT

### WC Pages ###

Shop base: #9 - /donation-failed/
Cart: ❌ Page does not contain the [woocommerce_cart] shortcode or the woocommerce/cart block.
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: #12 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Charityheart Child
Version: 1.0.0
Author URL: https://themeforest.net/user/apustheme
Child Theme: ✔
Parent Theme Name: Charityheart
Parent Theme Version: 1.8
Parent Theme Author URL: https://apusthemes.com/
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: –

### Admin ###

Enabled Features: activity-panels
analytics
coupons
customer-effort-score-tracks
experimental-products-task
experimental-import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
multichannel-marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings

Daily Cron: ✔ Next scheduled: 2023-01-29 07:04:17 +00:00
Options: ✔
Notes: 36
Onboarding: completed

### Action Scheduler ###

Complete: 91
Oldest: 2022-12-29 03:57:01 +0000
Newest: 2023-01-28 07:12:08 +0000

Pending: 6
Oldest: 2023-01-28 11:35:48 +0000
Newest: 2023-01-31 09:43:46 +0000

### Status report information ###

Generated at: 2023-01-28 07:16:33 +00:00
`

**Comment by jonas-hoebenreich** [comment]
Hi incmak,
thanks for reaching out. Can you please try the following steps?
1. Update WooCommerce Donation Platform for WooCommerce to v1.2.9
2. Update WooCommerce Database: https://woocommerce.com/document/how-to-update-woocommerce/#woocommerce-data-update-notice

This will hopefully resolve the issue.
Best regards
Jonas

**Comment by incmak** [comment]
Yes. extremely sorry, it was the database issue.
