### ISSUE TITLE
Multi currency support

### ISSUE THREAD

**Issue by pecakpawel** [jonas-hoebenreich/wc-donation-platform#39]
I would like to add multi-currency support to my platform. I saw on the project website that it is in the plans. I am looking forward to updating the platform to support multiple currencies

**Comment by jonas-hoebenreich** [comment]
Hi pecakpawel,

thanks for reaching out. I'm not 100% sure what you mean with this sentence: I am looking forward to updating the platform to support multiple currencies. Do you want to contribute? If so, I am very happy if you open a pull request. Or are you just expressing that you would be happy if I implemented the feature?

Best
Jonas

**Comment by jonas-hoebenreich** [comment]
You can follow this guide on how to set up multiple currencies: https://wcdp.jonh.eu/documentation/integrations/use-multiple-currencies-currency-switcher/
