### ISSUE TITLE
 Fatal error: Uncaught Error: Class "WPO\WC\PDF_Invoices\Compatibility\Order" not found

### ISSUE THREAD

**Issue by kprovance** [jonas-hoebenreich/wc-donation-platform#40]
**Describe the bug**
While on the WooCommerce "My Account" clicking the "Donation" selection on the menu on the left generates a fatal error.

**To Reproduce**
1. Access the "My Account" screen as provided by WooCommerce.
2. Click on "Donations"
3. See error

**Expected behavior**
To view whatever screen is available for DOnations within the My Account screen. This is the first time I've tried it, I don't know what it looks like yet and can't say for certain.

**Error Log**
[17-Jul-2023 15:59:19 UTC] PHP Fatal error:  Uncaught Error: Class "WPO\WC\PDF_Invoices\Compatibility\Order" not found in <site-dir>/wp-content/plugins/wc-donation-platform/includes/integrations/woocommerce-pdf-invoices-packing-slips/class-wcdp-thank-you-certificate.php:60
Stack trace:
-0 <site-dir>/wp-includes/class-wp-hook.php(308): WPO\WC\PDF_Invoices\Documents\WCDP_Thank_You_Certificate->WPO\WC\PDF_Invoices\Documents\{closure}(Array, Object(WC_Order))
-1 <site-dir>/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
-2 <site-dir>/wp-content/plugins/woocommerce-pdf-invoices-packing-slips/includes/class-wcpdf-frontend.php(61): apply_filters('wpo_wcpdf_myacc...', Array, Object(WC_Order))
-3 <site-dir>/wp-includes/class-wp-hook.php(308): WPO\WC\PDF_Invoices\Frontend->my_account_pdf_link(Array, Object(WC_Order))
-4 <site-dir>/wp-includes/plugin.php(205): WP_Hook->apply_filters(Array, Array)
-5 <site-dir>/wp-content/plugins/woocommerce/includes/wc-account-functions.php(305): apply_filters('woocommerce_my_...', Array, Object(WC_Order))
-6 <site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/myaccount/orders.php(64): wc_get_account_orders_actions(Object(WC_Order))
-7 <site-dir>/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/home2/tpasoftc...')
-8 <site-dir>/wp-content/plugins/woocommerce/includes/wc-template-functions.php(3253): wc_get_template('myaccount/order...', Array)
-9 <site-dir>/wp-includes/class-wp-hook.php(308): woocommerce_account_orders(1)
-10 <site-dir>/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
-11 <site-dir>/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
-12 <site-dir>/wp-content/plugins/woocommerce/includes/wc-template-functions.php(3201): do_action('woocommerce_acc...', '')
-13 <site-dir>/wp-includes/class-wp-hook.php(308): woocommerce_account_content('')
-14 <site-dir>/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
-15 <site-dir>/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
-16 <site-dir>/wp-content/plugins/woocommerce/templates/myaccount/my-account.php(34): do_action('woocommerce_acc...')
-17 <site-dir>/wp-content/plugins/woocommerce/includes/wc-core-functions.php(345): include('/home2/tpasoftc...')
-18 <site-dir>/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php(123): wc_get_template('myaccount/my-ac...', Array)
-19 <site-dir>/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php(72): WC_Shortcode_My_Account::my_account('')
-20 <site-dir>/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(72): WC_Shortcode_My_Account::output('')
-21 <site-dir>/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php(115): WC_Shortcodes::shortcode_wrapper(Array, '')
-22 <site-dir>/wp-includes/shortcodes.php(355): WC_Shortcodes::my_account('', '', 'woocommerce_my_...')
-23 [internal function]: do_shortcode_tag(Array)
-24 <site-dir>/wp-includes/shortcodes.php(227): preg_replace_callback('/\\[(\\[?)(woocom...', 'do_shortcode_ta...', '[woocommerce_my...')
-25 <site-dir>/wp-includes/class-wp-hook.php(308): do_shortcode('[woocommerce_my...')
-26 <site-dir>/wp-includes/plugin.php(205): WP_Hook->apply_filters('[woocommerce_my...', Array)
-27 <site-dir>/wp-includes/post-template.php(255): apply_filters('the_content', '<!-- wp:shortco...')
-28 <site-dir>/wp-content/themes/seele/layout/page-standard.php(56): the_content()
-29<site-dir>/wp-includes/template.php(785): require('/home2/tpasoftc...')
-30 <site-dir>/wp-includes/template.php(718): load_template('/home2/tpasoftc...', false, Array)
-31 <site-dir>/wp-includes/general-template.php(204): locate_template(Array, true, false, Array)
-32 <site-dir>/wp-content/themes/seele/page.php(26): get_template_part('layout/page', 'standard')
-33 <site-dir>/wp-includes/template-loader.php(106): include('/home2/tpasoftc...')
-34 <site-dir>/wp-blog-header.php(19): require_once('/home2/tpasoftc...')
-35 <site-dir>/index.php(17): require('/home2/tpasoftc...')
-36 {main}
  thrown in /home2/tpasoftc/public_html/svlstudios/wp-content/plugins/wc-donation-platform/includes/integrations/woocommerce-pdf-invoices-packing-slips/class-wcdp-thank-you-certificate.php on line 60

**Device (please complete the following information):**
 - Device: Desktop Computer
 - OS: Windows 10
 - Browser: Chrome 
 - Version: v114.0.0.0 

**WordPress Environment**

`
### WordPress Environment ###

WordPress address (URL): https://www.svlstudios.com/wls
Site address (URL): https://www.svlstudios.com/wls
WC Version: 7.8.2
REST API Version: ✔ 7.8.2
WC Blocks Version: ✔ 10.2.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.2.2
WP Multisite: ✔
WP Memory Limit: 512 MB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.0.29
PHP Post Max Size: 516 MB
PHP Time Limit: 600
PHP Max Input Vars: 1000
cURL Version: 8.1.2
OpenSSL/1.1.1u

SUHOSIN Installed: –
MySQL Version: 5.7.23-23
Max Upload Size: 63 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 7.8.2
WC Database Prefix: wp_uhgc_27_
Total Database Size: 10.11MB
Database Data Size: 8.02MB
Database Index Size: 2.09MB
wp_uhgc_27_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uhgc_27_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_uhgc_27_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uhgc_27_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_uhgc_27_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uhgc_27_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uhgc_27_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uhgc_27_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uhgc_27_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uhgc_27_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_actionscheduler_actions: Data: 0.05MB + Index: 0.11MB + Engine InnoDB
wp_uhgc_27_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uhgc_27_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uhgc_27_comments: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_uhgc_27_gla_attribute_mapping_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uhgc_27_gla_budget_recommendations: Data: 0.22MB + Index: 0.14MB + Engine InnoDB
wp_uhgc_27_gla_merchant_issues: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uhgc_27_gla_shipping_rates: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uhgc_27_gla_shipping_times: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_options: Data: 5.02MB + Index: 0.08MB + Engine InnoDB
wp_uhgc_27_postmeta: Data: 0.41MB + Index: 0.25MB + Engine InnoDB
wp_uhgc_27_posts: Data: 0.09MB + Index: 0.06MB + Engine InnoDB
wp_uhgc_27_revslider_css: Data: 0.13MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_revslider_css_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_revslider_layer_animations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uhgc_27_revslider_layer_animations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uhgc_27_revslider_navigations: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uhgc_27_revslider_navigations_bkp: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uhgc_27_revslider_sliders: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_revslider_sliders_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_revslider_slides: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_revslider_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_revslider_static_slides: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_revslider_static_slides_bkp: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uhgc_27_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uhgc_27_term_relationships: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uhgc_27_vicatna_product_price: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uhgc_27_visitor_maps_ge: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uhgc_27_visitor_maps_st: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uhgc_27_visitor_maps_wo: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_wcpdf_invoice_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uhgc_27_wcpdf_thank_you_certificate_number: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uhgc_27_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_uhgc_27_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uhgc_27_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uhgc_27_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uhgc_27_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uhgc_27_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_uhgc_27_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_uhgc_27_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_uhgc_27_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
wp_uhgc_27_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_uhgc_27_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_27_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_uhgc_blogmeta: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_uhgc_blogs: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_uhgc_registration_log: Data: 0.00MB + Index: 0.00MB + Engine MyISAM
wp_uhgc_signups: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_uhgc_site: Data: 0.00MB + Index: 0.01MB + Engine MyISAM
wp_uhgc_sitemeta: Data: 0.71MB + Index: 0.02MB + Engine MyISAM
wp_uhgc_usermeta: Data: 0.06MB + Index: 0.04MB + Engine MyISAM
wp_uhgc_users: Data: 0.00MB + Index: 0.01MB + Engine MyISAM

### Post Type Counts ###

attachment: 21
nav_menu_item: 7
page: 16
post: 2
product: 10
revision: 10
shop_order: 2
shop_subscription: 1
wpcf7_contact_form: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (23) ###

Query Monitor: by John Blackbourn – 3.13.1
Redux Framework: by Team Redux – 4.4.4
Ultimate Addons for WPBakery Page Builder: by Brainstorm Force – 3.19.15
Classic Editor: by WordPress Contributors – 1.6.3
Classic Widgets: by WordPress Contributors – 0.3
Contact Form 7: by Takayuki Miyoshi – 5.7.7
Google Listings and Ads: by WooCommerce – 2.4.11
WPBakery Page Builder: by Michael M - WPBakery.com – 6.13.0
Requite Core: by SVL Studios – 1.1.14
Slider Revolution: by ThemePunch – 6.6.14
Subscriptions For WooCommerce: by WP Swings – 1.5.2
Who's Online with Visitor Maps: by Kevin Provance d/b/a SVL Studios – 2.0
Donation Platform for WooCommerce: Fundraising & Donation Management: by Jonas Höbenreich – 1.2.10
WooCommerce Stripe Gateway: by WooCommerce – 7.4.1
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.5.6
WooCommerce: by Automattic – 7.8.2
Optimize Database after Deleting Revisions: by CAGE Web Design | Rolf van Gelder Eindhoven The Netherlands – 5.0.110
WP Migrate DB Pro: by Delicious Brains – 1.8.1
WP Migrate DB Pro CLI: by Delicious Brains – 1.3.2
WP Migrate DB Pro Media Files: by Delicious Brains – 1.4.9
WP Migrate DB Pro Multisite Tools: by Delicious Brains – 1.2
WPBruiser: by Mihai Chelaru – 3.1.43
Force Plugin Updates Check: by Pippin Williamson – 1.0.2

### Inactive Plugins (59) ###

Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
Bad Behavior: by Michael Hampton – 2.2.24
bbPress: by The bbPress Contributors – 2.6.9
BuddyPress: by The BuddyPress Community – 11.2.0
Cleanup Duplicate Meta: by WP Developers Club and Tonya – 1.0.2
Cloudflare: by Cloudflare Inc. – 4.12.0
Coming Soon Page, Maintenance Mode, Landing Pages & WordPress Website Builder by SeedProd: by SeedProd – 6.15.7
Debug Bar: by wordpressdotorg – 1.1.4
Download Media Library: by marcelotorres – 0.2.1
downML - Download Media Library: by aneeskA contact@aneeska.com – 0.4.6
Envato Market: by Envato – 2.0.6
Envato Theme Check: by Scott Parry – 20180222
Envato WordPress Toolkit: by Envato – 1.7.3
EWWW Image Optimizer: by Exactly WWW – 7.1.0
MC4WP: Mailchimp for WordPress: by ibericode – 4.9.6
Menu Exporter: by Joe Hoyle - Human Made Limited – 1
Page Links To: by Mark Jaquith – 3.3.6
Password Protected: by WPExperts – 2.6.3.1
Qixi Core: by SVL Studios – 1.0.0
Quick Page/Post Redirect Plugin: by anadnet – 5.2.4
Redux Extensions: by Team Redux – 1.0.0
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.5
Seele Demo Content Importer: by Requite Designs – 1.1.0
Slider Revolution Background Slicey Add-On: by ThemePunch – 1.0.2
Smush: by WPMU DEV – 3.13.2
Stackable - Gutenberg Blocks: by Gambit Technologies Inc – 3.10.0
Svl-OAuth: by Kevin Provance – 1.0.0
Theme Check: by Theme Review Team – 20230417
ThemeForest-Check: by Japh – 1.0.4
Velvet Blues Update URLs: by VelvetBlues.com – 3.2.10
Visitor Maps and Who's Online: by Mike Challis – 1.5.8.12
Visitor Maps Extended Referer Field: by Jason Lau – 1.2.6
Visitor Maps Geolocation Addon: by Mike Challis – 1.0
W3 Total Cache: by BoldGrid – 2.3.3
Widget Importer & Exporter: by ChurchThemes.com – 1.6.1
WooCommerce Product Add-ons: by WooCommerce – 2.9.5
WooCommerce Shipment Tracking: by WooCommerce – 1.6.11
WooCommerce Shipping & Tax: by WooCommerce – 2.3.0 (update to version 2.3.1 is available)
WooCommerce Subscriptions: by Prospress Inc. – 2.2.20
WordPress Importer: by wordpressdotorg – 0.8.1
WP-Sweep: by Lester 'GaMerZ' Chan – 1.1.8
WP Attachment Export: by Peter Harlacher – 0.3.3
WP SMS for WordPress: by WordPress SMS Team – 1.5.1
Yoast SEO: by Team Yoast – 20.11

### Dropin Plugins (1) ###

install.php: install.php

### Must Use Plugins (2) ###

SSO: by Garth Mortensen
Mike Hansen – 0.4

WP Migrate DB Pro Compatibility: by Delicious Brains – 1.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #46 - /shop/
Cart: #47 - /cart/
Checkout: #48 - /checkout/
My account: #49 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Seele
Version: 1.1.2
Author URL: https://www.svlstudios.com
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔

### Templates ###

Archive Template: Your theme has a woocommerce.php file
you will not be able to override the woocommerce/archive-product.php custom template since woocommerce.php has priority over archive-product.php. This is intended to prevent display issues.

Overrides: seele/woocommerce/cart/cart.php
seele/woocommerce/cart/mini-cart.php
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/cart-errors.php version - is out of date. The core version is 3.5.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/form-billing.php version - is out of date. The core version is 3.6.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/form-checkout.php version - is out of date. The core version is 3.5.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/form-login.php version - is out of date. The core version is 3.8.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/order-receipt.php version - is out of date. The core version is 3.2.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/payment.php version - is out of date. The core version is 7.8.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/review-order.php version - is out of date. The core version is 5.2.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/thankyou.php version - is out of date. The core version is 3.7.0
seele/woocommerce/content-product.php
seele/woocommerce/content-single-product.php
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/admin-cancelled-order.php
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/admin-failed-order.php
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/admin-new-order.php
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-completed-order.php
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-invoice.php
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-new-account.php version 3.7.0 is out of date. The core version is 6.0.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-note.php
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-on-hold-order.php version 3.7.0 is out of date. The core version is 7.3.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-processing-order.php
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-refunded-order.php
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/email-addresses.php version 3.9.0 is out of date. The core version is 5.6.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/email-customer-details.php
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/email-order-details.php
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/admin-cancelled-order.php
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/admin-failed-order.php
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/admin-new-order.php version - is out of date. The core version is 3.7.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-completed-order.php version - is out of date. The core version is 3.7.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-invoice.php version - is out of date. The core version is 3.7.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-note.php version - is out of date. The core version is 3.7.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-on-hold-order.php version - is out of date. The core version is 7.3.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-processing-order.php version - is out of date. The core version is 3.7.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-refunded-order.php version - is out of date. The core version is 3.7.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/email-addresses.php version - is out of date. The core version is 5.6.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/email-customer-details.php version - is out of date. The core version is 3.4.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/email-order-details.php version - is out of date. The core version is 3.7.0
seele/woocommerce/global/quantity-input.php
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/loop/no-products-found.php version - is out of date. The core version is 7.8.0
seele/woocommerce/loop/sale-flash.php
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/myaccount/dashboard.php version - is out of date. The core version is 4.4.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/myaccount/downloads.php version - is out of date. The core version is 7.8.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/myaccount/my-address.php version - is out of date. The core version is 2.6.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/myaccount/orders.php version - is out of date. The core version is 7.8.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/myaccount/view-order.php version - is out of date. The core version is 3.0.0
<site-dir>/wp-content/plugins/wc-donation-platform/includes/wc-templates/order/order-details.php version - is out of date. The core version is 7.8.0
seele/woocommerce/single-product/meta.php
seele/woocommerce/single-product/product-image.php
seele/woocommerce/single-product/related.php
seele/woocommerce/single-product/sale-flash.php
seele/woocommerce/single-product/tabs/additional-information.php
seele/woocommerce/single-product/tabs/description.php
seele/woocommerce/single-product/tabs/tabs.php
seele/woocommerce/single-product/up-sells.php

Outdated Templates: ❌
					
					
						Learn how to update

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: core-profiler
minified-js
new-product-management-experience
product-variation-management
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2023-07-17 20:33:30 -04:00
Options: ✔
Notes: 63
Onboarding: completed

### Action Scheduler ###

Complete: 41
Oldest: 2023-07-16 16:33:45 -0400
Newest: 2023-07-17 12:15:02 -0400

Failed: 5
Oldest: 2023-07-16 16:36:43 -0400
Newest: 2023-07-16 21:45:21 -0400

Pending: 4
Oldest: 2023-07-17 12:39:39 -0400
Newest: 2023-07-18 05:12:15 -0400

**Comment by jonas-hoebenreich** [comment]
Thanks for your message. Does the error only occur when you click on My Account -> Donations page, or also in the backend or when generating PDFs, for example?

**Comment by kprovance** [comment]
No problems when generating PDFs. The very latest version of the PDF Invoices & Packing Slips for WooCommerce plugin no longer has classes with the namespaces referenced in your plugin, and why the error occurs. I looked at the history of the PDF plugin. They removed those classes sometimes in the v3 release. Do you have their latest release? It's 3.5.6 as of 4 weeks ago.  Isn't it annoying when other developers do that? Backward compatibility is important. But, yes, the PR I sent you no longer relies on those classes in the PDF plugin.

FWIW, I totally dig this plugin. It works fantastically.

**Comment by jonas-hoebenreich** [comment]
Thank you so much for your positive feedback.
It is indeed annoying that the classes have been removed (although I could have been prepared for this). What puzzles me is why it still works in most cases.

**Comment by kprovance** [comment]
You're welcome. It's deserved.

If I had to guess based on my experience with developing plugins? Older versions. Folks not updating. They dropped the classes in question in v3.2.6.
