### ISSUE TITLE
High-Performance order storage (COT)

### ISSUE THREAD

**Issue by uhlhosting** [jonas-hoebenreich/wc-donation-platform#46]
**Is your feature request related to a problem? Please describe.**

⚠ This plugin is incompatible with the enabled WooCommerce feature 'High-Performance order storage (COT)', it shouldn't be activated. Manage WooCommerce features
--
 

<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">⚠ This plugin is incompatible with the enabled WooCommerce feature 'High-Performance order storage (COT)', it shouldn't be activated. [Manage WooCommerce features](https://africanbushdoctorz.com/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jonas-hoebenreich** [comment]
Hi uhlhosting,
sorry for not getting back to you.
I addressed this issue in version 1.3.0 of the plugin, so this is resolved :)
Best,
Jonas
