### ISSUE TITLE
Recovery fee issue not showing

### ISSUE THREAD

**Issue by KevAguirre** [jonas-hoebenreich/wc-donation-platform#47]
Hi there John! Hope everything is going great! I've been having issues with the recovery fee it's not showing, I installed the WordPress plugin correctly and followed the guide established for it to work.

But no success, the checkbox it's not showing.

**Comment by jonas-hoebenreich** [comment]
Hi KevAguirre,
thanks for reaching out.
Have you enabled to compatibility mode? Are you using a theme with a custom order review template?

Best,
Jonas
