### ISSUE TITLE
Update compatibility for WooCommerce 8.4 and Wordpress 6.4.2 

### ISSUE THREAD

**Issue by JantieWillie** [jonas-hoebenreich/wc-donation-platform#52]
Update the plugin so it can be used with the latest version of Woocommerce and Wordpress.

Due to an update to WooCommerce the plugin won't work.

**Comment by jonas-hoebenreich** [comment]
Hi JantieWillie,
can you please describe the issue with a bit more details? I have not been able to reproduce the error.
Best,
Jonas

**Comment by JantieWillie** [comment]
Goodmorning,

Due to an update on woocommerce you can't do this step anymore when making a product. the option is not there.

"Important: Activate Donation Project. Only products marked as Donation Project can be used in donation forms"

There is no donation form tab in either wordpress or woocommerce.





I tried a lot and we need this plugin since its the best out there that is free and useful with woocommerce and Mollie.



Greetings,


Jan-Willem van der Lingen

Social Media Manager & Vrijwilleger H2OEK


[https://lh7-us.googleusercontent.com/LfDoODanoIBnKmkFtnRZCl5ZE0HOXay_w2wLz_bdhjNE-QFm58ejhLvVK1D7Hk5x2l8Of7xlAa1Ch6xr1ctlZs8vm0cAFvLZ5aiX3oRGKjO6PdHSjeaARBe-4d-yXgbaNjaOvGFUSZwazf1prjOADr0]

T: (+31) 06-10411482

E: ***@***.******@***.***>

I: www.h2oek.com<http://www.h2oek.com/>


________________________________
Van: Jonas Höbenreich ***@***.***>
Verzonden: zaterdag 13 januari 2024 11:19
Aan: jonas-hoebenreich/wc-donation-platform ***@***.***>
CC: Jan-Willem Van der Lingen ***@***.***>; Author ***@***.***>
Onderwerp: Re: [jonas-hoebenreich/wc-donation-platform] Update compatibility for WooCommerce 8.4 and Wordpress 6.4.2 (Issue #52)


Hi JantieWillie,
can you please describe the issue with a bit more details? I have not been able to reproduce the error.
Best,
Jonas

**Comment by jonas-hoebenreich** [comment]
I am using WooCommerce 8.5 and WordPress 6.4.2 and everything seems to work fine.
![image](https://github.com/jonas-hoebenreich/wc-donation-platform/assets/64426524/702a774b-d503-4ada-9599-df2e708d48ec)
Can you please share a screenshot of this section in your environment?

Can you please check if you have the New product editor disabled? (WooCommerce settings -> Advanced -> Features, yoursite.com/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features)
![image](https://github.com/jonas-hoebenreich/wc-donation-platform/assets/64426524/11d1cf33-cc4c-4405-b773-bf8a5924f0e6)

Best,
Jonas

**Comment by JantieWillie** [comment]
Thanks, indeed new product editor was on, maybe add it on the FAQ instructions?

Its solved.


Best,
Jan-Willem


Met vriendelijke groet,


Jan-Willem van der Lingen

Social Media Manager & Vrijwilliger H2OEK


[https://lh7-us.googleusercontent.com/LfDoODanoIBnKmkFtnRZCl5ZE0HOXay_w2wLz_bdhjNE-QFm58ejhLvVK1D7Hk5x2l8Of7xlAa1Ch6xr1ctlZs8vm0cAFvLZ5aiX3oRGKjO6PdHSjeaARBe-4d-yXgbaNjaOvGFUSZwazf1prjOADr0]

T: (+31) 06-10411482

E: ***@***.******@***.***>

I: www.h2oek.com<http://www.h2oek.com/>


________________________________
Van: Jonas Höbenreich ***@***.***>
Verzonden: zaterdag 13 januari 2024 11:40
Aan: jonas-hoebenreich/wc-donation-platform ***@***.***>
CC: Jan-Willem Van der Lingen ***@***.***>; Author ***@***.***>
Onderwerp: Re: [jonas-hoebenreich/wc-donation-platform] Update compatibility for WooCommerce 8.4 and Wordpress 6.4.2 (Issue #52)


I am using WooCommerce 8.5 and WordPress 6.4.2 and everything seems to work fine.
image.png (view on web)<https://github.com/jonas-hoebenreich/wc-donation-platform/assets/64426524/702a774b-d503-4ada-9599-df2e708d48ec>
Can you please share a screenshot of this section in your environment?

Can you please check if you have the New product editor disabled? (WooCommerce settings -> Advanced -> Features, yoursite.com/wp-admin/admin.php?page=wc-settings&tab=advanced&section=features)
image.png (view on web)<https://github.com/jonas-hoebenreich/wc-donation-platform/assets/64426524/11d1cf33-cc4c-4405-b773-bf8a5924f0e6>

Best,
Jonas

**Comment by jonas-hoebenreich** [comment]
I've added notes to the documentation: https://wcdp.jonh.eu/documentation/getting-started/first-steps/ :)
