### ISSUE TITLE
wcdp_range_slider_steps filter is not working when using the Just an Input Box layout

### ISSUE THREAD

**Issue by kkmiller09** [jonas-hoebenreich/wc-donation-platform#55]
**Describe the bug**

**To Reproduce**
1. Created a product using the Just an Input box layout
2. Added the shortcode to my page.
3. On Step 1 the input box steps are defaulted to 0.01.
4 Add the following code to my functions.php to increment by one dollar.

/*Set the stepper to one dollar increments.*/
add_filter('wcdp_range_slider_steps', 'fm_range_slider_steps');
function fm_range_slider_steps($step) {	
		return 1.00;        
}

**Expected behavior**
I expected the step to be set to 1.00.  It remained 0.01.

**Resolution Suggestion**
I believe the issues is located in wcdp_step_1_amount.php, line 29. Instead of $wcdp_price_decimals, I believe the filter should be used.

![image](https://github.com/jonas-hoebenreich/wc-donation-platform/assets/3706035/3f00f9bd-7816-4ae9-83cc-3500548fced1)

**Comment by jonas-hoebenreich** [comment]
Hi there,
thanks for reaching out.
wcdp_range_slider_steps controls the step increment of the range slider (e.g. https://wcdp.jonh.eu/demos/range-slider-style-2/).
The correct filter for the decimals of the amount input box is wcdp_donation_amount_decimals. See https://wcdp.jonh.eu/documentation/advanced/change-donation-amount-increment/
So the correct script should be:
`add_filter('wcdp_donation_amount_decimals', function() {
	return 1;
});`
Best,
Jonas

**Comment by kkmiller09** [comment]
Thank you so much for the quick reply.  

A side effect we're finding of this approach is that the user is no longer able to enter an amount with change manually.  It forces the amount to have no decimals.

![image](https://github.com/jonas-hoebenreich/wc-donation-platform/assets/3706035/63bbbc0e-0103-4d4b-9649-16e260cc40c5)

**Comment by jonas-hoebenreich** [comment]
Yes, that's true. Setting an increment of 1 will force users to only enter increments of 1 ;)
