### ISSUE TITLE
Woocommerce email not showing all details

### ISSUE THREAD

**Issue by myhappyidea** [jonas-hoebenreich/wc-donation-platform#57]
**Describe the bug**
I added some code to functions.php to add before the table the description of the product and its photo. I use wc-donation-platform with woocommerce subscriptions.
When its a regular donation, the description + photos shows up, but when its a recurring one, it does not.

**To Reproduce**
1. Make a recurring order.
2. Check out email, no details at the beginning.
3. 

CODE ADDED:
// adds the product description before the order table in the completed order email
add_action( 'woocommerce_email_before_order_table', 'add_content_before_order_table', 99, 4 );
function add_content_before_order_table( $order, $sent_to_admin, $plain_text, $email ) {

    // only for the email of the completed order
    if ( ! $email->id == 'customer_completed_order' ) {
        return;
    }

    // initializes the array with all product descriptions
    $descriptions = array();

    // for each product ordered
    foreach ( $order->get_items() as $order_item  ) {
        $product = $order_item->get_product();
        // get the product description
        if ( $product->get_description() ) {
            $descriptions[] = $product->get_description();
        }
    }

    // if the $descriptions is not empty it shows it
    if ( ! empty( $descriptions ) ) {
        foreach ( $descriptions as $content ) {
            echo '<p>' . $content . '</p>';
        }
    }

}

**Expected behavior**
Product description should appear before the donation table / order table.

**Error Log**
None

**Screenshots**
<img width="890" alt="recurring" src="https://github.com/jonas-hoebenreich/wc-donation-platform/assets/23118054/85efb082-b0d1-4057-87eb-06fa303ad9fd">
<img width="857" alt="donation not recurring" src="https://github.com/jonas-hoebenreich/wc-donation-platform/assets/23118054/3f0f2e19-1655-4964-ba0a-bbf736684768">

**Device (please complete the following information):**
 - Device: Macbook air
 - OS: Maverick OS
 - Browser Chrome latest version

**Additional context**

**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): https://pruebas.proyectohombremadrid.org
Site address (URL): https://pruebas.proyectohombremadrid.org
WC Version: 8.5.2
REST API Version: ✔ 8.5.2
WC Blocks Version: ✔ 11.8.0-dev
Action Scheduler Version: ✔ 3.7.1
Log Directory Writable: ✔
WP Version: 6.4.3
WP Multisite: –
WP Memory Limit: 512 MB
WP Debug Mode: –
WP Cron: ✔
Language: es_ES
External object cache: –

### Server Environment ###

Server Info: Apache
PHP Version: 8.1.27
PHP Post Max Size: 64 MB
PHP Time Limit: 120
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.3.39-MariaDB-0ubuntu0.20.04.2
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.5.2
WC Database Prefix: yfcCFmLyN_
Total Database Size: 100.07MB
Database Data Size: 86.34MB
Database Index Size: 13.73MB
yfcCFmLyN_woocommerce_sessions: Data: 2.02MB + Index: 0.06MB + Engine InnoDB
yfcCFmLyN_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
yfcCFmLyN_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
yfcCFmLyN_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yfcCFmLyN_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yfcCFmLyN_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_actionscheduler_actions: Data: 2.02MB + Index: 0.67MB + Engine InnoDB
yfcCFmLyN_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_actionscheduler_logs: Data: 1.47MB + Index: 0.36MB + Engine InnoDB
yfcCFmLyN_cmplz_cookiebanners: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yfcCFmLyN_cmplz_cookies: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
yfcCFmLyN_cmplz_services: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yfcCFmLyN_commentmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_comments: Data: 0.05MB + Index: 0.09MB + Engine InnoDB
yfcCFmLyN_ewwwio_images: Data: 2.52MB + Index: 1.66MB + Engine InnoDB
yfcCFmLyN_ewwwio_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_frm_fields: Data: 0.25MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_frm_forms: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_frm_items: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
yfcCFmLyN_frm_item_metas: Data: 0.08MB + Index: 0.08MB + Engine InnoDB
yfcCFmLyN_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yfcCFmLyN_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yfcCFmLyN_options: Data: 7.02MB + Index: 0.16MB + Engine InnoDB
yfcCFmLyN_postmeta: Data: 6.11MB + Index: 1.84MB + Engine InnoDB
yfcCFmLyN_posts: Data: 56.41MB + Index: 0.56MB + Engine InnoDB
yfcCFmLyN_rank_math_internal_links: Data: 0.09MB + Index: 0.05MB + Engine InnoDB
yfcCFmLyN_rank_math_internal_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yfcCFmLyN_relevanssi: Data: 5.06MB + Index: 6.48MB + Engine InnoDB
yfcCFmLyN_relevanssi_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yfcCFmLyN_smush_dir_images: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_strong_views: Data: 0.14MB + Index: 0.00MB + Engine InnoDB
yfcCFmLyN_termmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_terms: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_term_relationships: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_term_taxonomy: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_usermeta: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_users: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
yfcCFmLyN_wc_admin_notes: Data: 0.08MB + Index: 0.00MB + Engine InnoDB
yfcCFmLyN_wc_admin_note_actions: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yfcCFmLyN_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_wc_orders: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
yfcCFmLyN_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
yfcCFmLyN_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
yfcCFmLyN_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
yfcCFmLyN_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
yfcCFmLyN_wc_product_attributes_lookup: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_wc_product_meta_lookup: Data: 0.02MB + Index: 0.09MB + Engine InnoDB
yfcCFmLyN_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yfcCFmLyN_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_wpfm_backup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yfcCFmLyN_wpmailsmtp_debug_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yfcCFmLyN_wpmailsmtp_tasks_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
yfcCFmLyN_wpml_mails: Data: 1.52MB + Index: 0.02MB + Engine InnoDB
yfcCFmLyN_wpr_rocket_cache: Data: 0.06MB + Index: 0.08MB + Engine InnoDB
yfcCFmLyN_wpr_rucss_used_css: Data: 0.06MB + Index: 0.09MB + Engine InnoDB

### Post Type Counts ###

attachment: 355
copy-to-clipboard: 1
custom_css: 2
customize_changeset: 5
et_body_layout: 3
et_footer_layout: 1
et_header_layout: 1
et_pb_layout: 17
et_template: 10
et_theme_builder: 1
frm_form_actions: 48
frm_styles: 1
groovy_menu_preset: 1
nav_menu_item: 67
page: 74
post: 145
product: 3
product_variation: 10
revision: 2662
shop_order: 21
shop_order_refund: 6
shop_subscription: 4
wapf_product: 2
wp_global_styles: 2
wpm-testimonial: 102
yaymail_template: 11

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (36) ###

Copy Anything to Clipboard: by Clipboard Team – 3.5.1
Complianz | GDPR/CCPA Cookie Consent: by Really Simple Plugins – 6.5.6
Joinchat: by Creame – 5.0.16
Disable Comments: by WPDeveloper – 2.4.5
Divi Booster: by Dan Mossop – 4.3.6
EWWW Image Optimizer: by Exactly WWW – 7.2.3
Flexible Checkout Fields: by WP Desk – 3.6.0
Formidable Forms Pro: by Strategy11 – 6.7.1
Formidable Forms: by Strategy11 Form Builder Team – 6.8
Gallery Custom Links: by Jordy Meow – 2.1.8
Site Kit by Google: by Google – 1.118.0
Groovy Menu: by Grooni – 2.6.3
Instant Images: by Darren Cooney – 6.1.1
Loco Translate: by Tim Whitlock – 2.6.6
Mailchimp for WooCommerce: by Mailchimp – 3.6
Maintenance: by WebFactory Ltd – 4.08
Page Links To: by Mark Jaquith – 3.3.6
Payment Methods by Product & Country for WooCommerce: by WPFactory – 1.7.8
Post Carousel Divi (Premium): by Learnhowwp.com – 1.2
Post Types Order: by Nsp Code – 2.1.2
Really Simple SSL: by Really Simple Plugins – 7.2.2
Relevanssi: by Mikko Saari – 4.22.0
Rank Math SEO: by Rank Math – 1.0.211
SEPA Payment Gateway for WooCommerce: by Nhat Huynh Van – 1.0.0
Snazzy Maps: by Snazzy Maps – 1.4.0
Strong Testimonials: by WPChill – 3.1.11
Donation Platform for WooCommerce: Fundraising & Donation Management: by Jonas Höbenreich – 1.3.0
WooCommerce Servired/RedSys Spain Gateway: by José Conti – 20.4.0
WooCommerce Stripe Gateway: by WooCommerce – 7.9.1
Woo Subscriptions: by WooCommerce – 5.9.0
WooCommerce: by Automattic – 8.5.2
WP File Manager: by mndpsingh287 – 7.2.2
WP Mail Logging: by WP Mail Logging Team – 1.12.0
WP Mail SMTP: by WP Mail SMTP – 3.11.1
WP-PageNavi: by Lester 'GaMerZ' Chan – 2.94.1
WP Rocket: by WP Media – 3.15.8.1

### Inactive Plugins (4) ###

Autocomplete WooCommerce Orders: by QuadLayers – 3.2.0
Pasarela Unificada de Redsys para WooCommerce: by Redsys Servicios de Procesamiento S.L. – 1.3.1
Smush: by WPMU DEV – 3.15.4
Temporary Login Without Password: by StoreApps – 1.8.3

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
maintenance.php: maintenance.php

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
subscription (subscription)
variable (variable)
variable subscription (variable-subscription)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to Woo.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: –
HPOS feature enabled: –
Order datastore: WC_Order_Data_Store_CPT
HPOS data sync enabled: –

### WC Pages ###

Shop base: #250333 - /tienda/
Cart: #250334 - /carrito/
Checkout: ❌ Page does not contain the [woocommerce_checkout] shortcode or the woocommerce/checkout block.
My account: #250336 - /mi-cuenta/
Terms and conditions: #250495 - /aviso-legal/

### Theme ###

Name: Proyecto Hombre Madrid
Version: 4.20.0.1679589348
Author URL: https://myhappyidea.com
Child Theme: ✔
Parent Theme Name: Divi
Parent Theme Version: 4.24.0
Parent Theme Author URL: http://www.elegantthemes.com
WooCommerce Support: ✔

### Templates ###

Overrides: /var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/cart-errors.php version - is out of date. The core version is 3.5.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/form-billing.php version - is out of date. The core version is 3.6.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/form-checkout.php version - is out of date. The core version is 3.5.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/form-login.php version - is out of date. The core version is 3.8.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/order-receipt.php version - is out of date. The core version is 3.2.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/payment.php version - is out of date. The core version is 8.1.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/review-order.php version - is out of date. The core version is 5.2.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/thankyou.php version - is out of date. The core version is 8.1.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/admin-cancelled-order.php
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/admin-failed-order.php
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/admin-new-order.php
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-completed-order.php
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-invoice.php
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-new-account.php version 3.7.0 is out of date. The core version is 6.0.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-note.php
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-on-hold-order.php version 3.7.0 is out of date. The core version is 7.3.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-processing-order.php
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-refunded-order.php
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/email-addresses.php version 3.9.0 is out of date. The core version is 5.6.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/email-customer-details.php
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/email-order-details.php
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/admin-cancelled-order.php
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/admin-failed-order.php
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/admin-new-order.php version - is out of date. The core version is 3.7.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-completed-order.php version - is out of date. The core version is 3.7.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-invoice.php version - is out of date. The core version is 3.7.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-note.php version - is out of date. The core version is 3.7.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-on-hold-order.php version - is out of date. The core version is 7.3.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-processing-order.php version - is out of date. The core version is 3.7.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-refunded-order.php version - is out of date. The core version is 3.7.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/email-addresses.php version - is out of date. The core version is 5.6.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/email-customer-details.php version - is out of date. The core version is 3.4.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/email-order-details.php version - is out of date. The core version is 3.7.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/loop/no-products-found.php version - is out of date. The core version is 7.8.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/myaccount/dashboard.php version - is out of date. The core version is 4.4.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/myaccount/downloads.php version - is out of date. The core version is 7.8.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/myaccount/my-address.php version - is out of date. The core version is 2.6.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/myaccount/orders.php version - is out of date. The core version is 8.5.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/myaccount/view-order.php version - is out of date. The core version is 3.0.0
/var/www/vhosts/proyectohombremadrid.org/pruebas.proyectohombremadrid.org/wp-content/plugins/wc-donation-platform/includes/wc-templates/order/order-details.php version - is out of date. The core version is 8.5.0

Outdated Templates: ❌
					
					
						Learn how to update

### Subscriptions ###

WCS_DEBUG: ✔ No
Subscriptions Mode: ✔ Live
Subscriptions Live URL: https://pruebas.proyectohombremadrid.org
Subscriptions-core Library Version: 6.7.0
Subscription Statuses: wc-active: 2
wc-pending: 2

WooCommerce Account Connected: ❌ No
Report Cache Enabled: ✔ Yes
Cache Update Failures: ✔ 0 failure

### Store Setup ###

Country / State: Spain — Madrid

### Subscriptions by Payment Gateway ###

Redsys Redirection (by José Conti): wc-active: 2
wc-pending: 2

### Payment Gateway Support ###

Redsys Redirection (by José Conti): products
tokenization
add_payment_method
refunds
pre-orders
subscriptions
subscription_cancellation
subscription_suspension
subscription_reactivation
subscription_amount_changes
subscription_date_changes
subscription_payment_method_change
subscription_payment_method_change_customer
subscription_payment_method_change_admin
multiple_subscriptions
yith_subscriptions
yith_subscriptions_scheduling
yith_subscriptions_pause
yith_subscriptions_multiple
yith_subscriptions_payment_date
yith_subscriptions_recurring_amount
redsys_preauth
redsys_token_r

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: customize-store
minified-js
new-product-management-experience
product-linked
settings
async-product-editor-category-field

Daily Cron: ✔ Next scheduled: 2024-02-05 17:33:13 +01:00
Options: ✔
Notes: 111
Onboarding: completed

### Action Scheduler ###

Canceled: 1
Oldest: 2024-02-05 10:59:23 +0000
Newest: 2024-02-05 10:59:23 +0000

Complete: 775
Oldest: 2024-01-05 14:17:02 +0000
Newest: 2024-02-05 13:42:57 +0000

Failed: 1,356
Oldest: 2023-06-19 13:38:32 +0000
Newest: 2024-02-05 10:52:55 +0000

Pending: 7
Oldest: 2024-02-05 14:21:59 +0000
Newest: 2024-03-05 12:53:02 +0000

### Status report information ###

Generated at: 2024-02-05 14:55:11 +01:00
`

**Comment by jonas-hoebenreich** [comment]
The subscriptions mail uses a different template with different actions. Please take a look at https://github.com/jonas-hoebenreich/wc-donation-platform/blob/main/includes/integrations/woocommerce-subscriptions/templates/emails/email-order-details.php
You have to use the filter 'woocommerce_email_before_' . $order_type . '_table'
Best,
Jonas
