### ISSUE TITLE
Urgent Assistance Needed: Outdated Templates and Compatibility Issues (Donation Platform for WooCommerce)

### ISSUE THREAD

**Issue by Teweldino** [jonas-hoebenreich/wc-donation-platform#58]
Dear Donation Platform for WooCommerce Support Team,

I am writing to seek your urgent assistance regarding my WooCommerce store. I am currently using the Donation Platform for WooCommerce plugin to facilitate donations, but I have encountered several concerning issues.

Upon inspecting my plugin files, I discovered numerous outdated template files across various sections, including checkout, emails, my account, and orders. Here's a list of some specific examples:

    cart-errors.php (version 3.5.0, core version 8.1.0)
    form-billing.php (version 3.6.0, core version 8.1.0)
    form-checkout.php (version 3.5.0, core version 8.1.0)
    myaccount/orders.php (version 8.5.0, core version 8.5.0)
    order/order-details.php (version 8.5.0, core version 8.5.0)

This significant version mismatch raises concerns about potential security vulnerabilities and compatibility issues in my donation platform.

I have already taken the following steps:

    Created a backup of my website.
    Updated the Donation Platform for WooCommerce plugin to the latest version
    Tested my website for functionality after the update.

However, I am still facing the following issues:

   /home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/cart-errors.php version - is out of date. The core version is 3.5.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/form-billing.php version - is out of date. The core version is 3.6.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/form-checkout.php version - is out of date. The core version is 3.5.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/form-login.php version - is out of date. The core version is 3.8.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/order-receipt.php version - is out of date. The core version is 3.2.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/payment.php version - is out of date. The core version is 8.1.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/review-order.php version - is out of date. The core version is 5.2.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/checkout/thankyou.php version - is out of date. The core version is 8.1.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/admin-cancelled-order.php,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/admin-failed-order.php,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/admin-new-order.php,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-completed-order.php,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-invoice.php,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-new-account.php version 3.7.0 is out of date. The core version is 6.0.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-note.php,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-on-hold-order.php version 3.7.0 is out of date. The core version is 7.3.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-processing-order.php,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/customer-refunded-order.php,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/email-addresses.php version 3.9.0 is out of date. The core version is 8.6.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/email-customer-details.php,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/email-order-details.php,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/admin-cancelled-order.php,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/admin-failed-order.php,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/admin-new-order.php version - is out of date. The core version is 3.7.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-completed-order.php version - is out of date. The core version is 3.7.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-invoice.php version - is out of date. The core version is 3.7.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-note.php version - is out of date. The core version is 3.7.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-on-hold-order.php version - is out of date. The core version is 7.3.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-processing-order.php version - is out of date. The core version is 3.7.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/customer-refunded-order.php version - is out of date. The core version is 3.7.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/email-addresses.php version - is out of date. The core version is 8.6.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/email-customer-details.php version - is out of date. The core version is 3.4.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/emails/plain/email-order-details.php version - is out of date. The core version is 3.7.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/loop/no-products-found.php version - is out of date. The core version is 7.8.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/myaccount/dashboard.php version - is out of date. The core version is 4.4.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/myaccount/downloads.php version - is out of date. The core version is 7.8.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/myaccount/my-address.php version - is out of date. The core version is 2.6.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/myaccount/orders.php version - is out of date. The core version is 8.5.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/myaccount/view-order.php version - is out of date. The core version is 3.0.0,
/home2/addis/public_html/wp-content/plugins/wc-donation-platform/includes/wc-templates/order/order-details.php version - is out of date. The core version is 8.5.0

I am concerned about the potential impact of these outdated templates and compatibility issues on my donation platform's security, performance, and user experience.

Therefore, I kindly request your urgent assistance in:

    Confirming if the updated plugin version should automatically resolve the outdated template issue.
    Providing guidance on any further manual steps I need to take to ensure all templates are using the latest versions.
    Troubleshooting any lingering compatibility issues after the update.

I am available for a call or further email communication to discuss this issue in more detail and provide any additional information you may require.

Thank you for your time and attention to this matter. I look forward to hearing from you soon.

Sincerely,
Tewelde A

**Comment by jonas-hoebenreich** [comment]
Hi Tewelde,

thanks for reaching out.
Outdated templates are not really an issue. If you want you can compare the templates provided by Donation Platform for WooCommerce with the latest templates by WooCommerce and open Pull requests if there are changes needed.

Best,
Jonas

**Comment by Teweldino** [comment]
Hi Jonas

yes, it is working well now. Could you please  help how to add the popup style on every end of  post (  article)? and at the end of home page. I am using WordPress jonah theme? 


> Hi Tewelde,
> 
> thanks for reaching out. Outdated templates are not really an issue. If you want you can compare the templates provided by Donation Platform for WooCommerce with the latest templates by WooCommerce and open Pull requests if there are changes needed.
> 
> Best, Jonas

**Comment by jonas-hoebenreich** [comment]
Hi sorry for the late reply. To be honest I'm not quite sure what the issue is exactly...
1. If you want to add the donation form to the end of your pages you can use a theme with Gutenberg full-site editing support to edit the page templates.
2. And what do you mean by this? "the lightbox discription text format is not working. it is taking the text with out space? help?"

Best, Jonas

**Comment by jonas-hoebenreich** [comment]
Closing this now, I updated all the templates :)
