### ISSUE TITLE
Order emails incorrectly labelled as donations

### ISSUE THREAD

**Issue by timmac-qmc** [jonas-hoebenreich/wc-donation-platform#63]
**Describe the bug**
We are sending additional woocommerce emails using the plugin https://en-gb.wordpress.org/plugins/custom-emails-for-woocommerce/.
In that email we use the shortcode [order_details] to display the order information. This is showing as "Donation #98" instead of "Order #98" when the order was for a completely different product that is not a donation product. 

**To Reproduce**
1. Setup 2 products, 1 normal 1 donation
2. Place order for normal product 
3. Check custom email with shortcode [order_details]

**Expected behavior**
Order details for normal products should say "Order" instead "Donations"

**Screenshots**
![image](https://github.com/jonas-hoebenreich/wc-donation-platform/assets/103250605/2e9f9351-1c57-4dbf-99d7-30576ac3586e)
![image](https://github.com/jonas-hoebenreich/wc-donation-platform/assets/103250605/2114a1fa-7b8e-49a8-82db-aa954f652417)

**Comment by jonas-hoebenreich** [comment]
Hi @timmac-qmc,

thanks for reaching out.
If you do not want the wording changes please activate the compatibility mode in the plugin's settings.

Best,
Jonas

**Comment by timmac-qmc** [comment]
I noticed that setting after raising the issue but it seems more like a work around than a fix. Surely the plugin can identify is the product is a donation or not and use the correct wording?

**Comment by jonas-hoebenreich** [comment]
The plugin is designed to turn WooCommerce into a donation platform. Making sure that wording changes are correctly applied according to the context is actually not that easy. But if you want to implement this, I'm always open to Pull requests :)
Please let me know if you want to work on this or otherwise I will close this issue soon.

Best, Jonas
