### ISSUE TITLE
Text field to display at maximum donation amount

### ISSUE THREAD

**Issue by cdhassell** [jonas-hoebenreich/wc-donation-platform#64]
I love this plugin, it is very helpful for us to raise donor funds. I just have a small suggestion to add. That is, when the user enters a donation amount large enough to hit the maximum, I'd like to show a message unique to that situation. If someone wants to give that much, I don't want them to get an error message and then go away with no follow up! We want to talk to that person to discuss their offer and make special  arrangements. Unfortunately that is a rare situation so it is not an urgent request but perhaps it is easily added. Thank you again for this great plugin.

**Comment by jonas-hoebenreich** [comment]
Thanks for the suggestion. I added it to my backlog but I will focus on other feature for now. In the meantime you can just add some generic form of donor contact to your website.
