### ISSUE TITLE
Customisation recommended for better donation experience!

### ISSUE THREAD

**Issue by procontentxyz** [jonas-hoebenreich/wc-donation-platform#7]
1. Directly show input for Custom donation amount, rather than first let user click on 'Other' to show the input.

Its little time taking....

Why dont show it normally, so that just enter amount and click next to proceed would work.

Also, no need to give check mark after input, just keep currency symbol & input, its enough.

I take several inputs before recommending this for the plugin.

Please consider.

![IMG_20211216_132543](https://user-images.githubusercontent.com/70431728/146330700-e7607668-a9d6-457f-9c66-af80d6decc68.jpg)

We can also have some space after currency symbol.

We could also wide this input to show placeholder text, like: "enter amount"

2. Give an option to show CUSTOM TITLE OR Product title by default (in bold) in popup below the product thumbnail, its also needed in some cases.

https://i.imgur.com/yCqiNzr_d.webp?maxwidth=640&shape=thumb&fidelity=medium

**Comment by jonas-hoebenreich** [comment]
By default, the input field is displayed as follows:
![image](https://user-images.githubusercontent.com/64426524/146343334-1433c857-0644-40b0-9743-4a219ff7b589.png)

You have selected "Radio/Button selection" as the layout for the Amount input, but have not entered any amounts. This is the only reason why it is displayed so strangely.
![image](https://user-images.githubusercontent.com/64426524/146343568-42805877-a1db-4449-af95-bfa8987d9f3b.png)

The plugin uses the default settings for currencies from WooCommerce. So if you want more space between the price and the currency sign, you can do that in the WooCommerce settings (example.com/wp-admin/admin.php?page=wc-settings):
![image](https://user-images.githubusercontent.com/64426524/146345214-2121f9b1-98a7-4606-9775-45d3d8f8edec.png)


2:
I am happy to include this in the future, currently the label cannot yet be comfortably adjusted.

**Comment by procontentxyz** [comment]
thanks for the quick reply. i appreciate this.

i am happily waiting for numer 2 option to get fulfilled.


thank you once again :)

**Comment by jonas-hoebenreich** [comment]
Just to let you know:
With the new update (Version 1.1.2), the donation amount title can now be adjusted in the settings (go to the "Donations" tab in the WooCommerce settings)
