### ISSUE TITLE
Issue with email templates

### ISSUE THREAD

**Issue by philipposmav** [jonas-hoebenreich/wc-donation-platform#70]
**Describe the bug**
There is an issue with the template styling for the WooCommerce emails. For example, take a look at the screenshot of one of the emails below: 
![image](https://github.com/jonas-hoebenreich/wc-donation-platform/assets/167525374/a270b292-915d-46fc-bb24-02b9dd2b7491)

Maybe the issue occurs when the below checkbox for compatibility is checked.
![image](https://github.com/jonas-hoebenreich/wc-donation-platform/assets/167525374/e6d7ad9d-75be-48f8-b51b-766c4482ea8f)

I tried using MailPoet to style the email template but it didn't work.

**WordPress Environment**
`
### WordPress Environment ###

WordPress address (URL): https://ihacyprus.org
Site address (URL): https://ihacyprus.org
WC Version: 8.8.2
REST API Version: ✔ 8.8.2
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.2
WP Multisite: –
WP Memory Limit: 128 MB
WP Debug Mode: –
WP Cron: ✔
Language: el
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.24.0
PHP Version: 8.1.22
PHP Post Max Size: 512 MB
PHP Time Limit: 300
PHP Max Input Vars: 5000
cURL Version: 8.5.0
OpenSSL/3.1.4

SUHOSIN Installed: –
MySQL Version: 5.7.35-38-log
Max Upload Size: 512 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.6.1
WC Database Prefix: wp_
Συνολικό μέγεθος βάσης δεδομένων: 52.67MB
Μέγεθος βάσης δεδομένων: 46.53MB
Μέγεθος ευρετηρίου βάσης δεδομένων: 6.14MB
wp_woocommerce_sessions: Δεδομένα: 0.23MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_woocommerce_api_keys: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_woocommerce_attribute_taxonomies: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_woocommerce_downloadable_product_permissions: Δεδομένα: 0.02MB + Ευρετήρια: 0.06MB + Μηχανή InnoDB.
wp_woocommerce_order_items: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_woocommerce_order_itemmeta: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_woocommerce_tax_rates: Δεδομένα: 0.02MB + Ευρετήρια: 0.06MB + Μηχανή InnoDB.
wp_woocommerce_tax_rate_locations: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_woocommerce_shipping_zones: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_woocommerce_shipping_zone_locations: Δεδομένα: 0.02MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
wp_woocommerce_shipping_zone_methods: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_woocommerce_payment_tokens: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_woocommerce_payment_tokenmeta: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_woocommerce_log: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_actionscheduler_actions: Δεδομένα: 1.45MB + Ευρετήρια: 0.78MB + Μηχανή InnoDB.
wp_actionscheduler_claims: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_actionscheduler_groups: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_actionscheduler_logs: Δεδομένα: 1.50MB + Ευρετήρια: 0.42MB + Μηχανή InnoDB.
wp_charitable_campaign_activities: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_charitable_campaign_donations: Δεδομένα: 0.02MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
wp_charitable_donation_activities: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_charitable_donormeta: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_charitable_donors: Δεδομένα: 0.02MB + Ευρετήρια: 0.06MB + Μηχανή InnoDB.
wp_cky_banners: Δεδομένα: 0.05MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_cky_cookies: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_cky_cookie_categories: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_commentmeta: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_comments: Δεδομένα: 0.02MB + Ευρετήρια: 0.09MB + Μηχανή InnoDB.
wp_e_events: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_e_notes: Δεδομένα: 0.02MB + Ευρετήρια: 0.17MB + Μηχανή InnoDB.
wp_e_notes_users_relations: Δεδομένα: 0.02MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
wp_e_submissions: Δεδομένα: 0.02MB + Ευρετήρια: 0.27MB + Μηχανή InnoDB.
wp_e_submissions_actions_log: Δεδομένα: 0.02MB + Ευρετήρια: 0.11MB + Μηχανή InnoDB.
wp_e_submissions_values: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_give_commentmeta: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_give_comments: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_give_donationmeta: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_give_donormeta: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_give_donors: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_give_formmeta: Δεδομένα: 0.09MB + Ευρετήρια: 0.06MB + Μηχανή InnoDB.
wp_give_log: Δεδομένα: 0.02MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
wp_give_migrations: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_give_revenue: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_give_sequential_ordering: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_give_sessions: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_give_subscriptionmeta: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_give_subscriptions: Δεδομένα: 0.02MB + Ευρετήρια: 0.06MB + Μηχανή InnoDB.
wp_gla_attribute_mapping_rules: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_gla_budget_recommendations: Δεδομένα: 0.19MB + Ευρετήρια: 0.11MB + Μηχανή InnoDB.
wp_gla_merchant_issues: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_gla_shipping_rates: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_gla_shipping_times: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_jetpack_sync_queue: Δεδομένα: 0.02MB + Ευρετήρια: 0.06MB + Μηχανή InnoDB.
wp_links: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_mailpoet_automations: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_mailpoet_automation_runs: Δεδομένα: 0.02MB + Ευρετήρια: 0.08MB + Μηχανή InnoDB.
wp_mailpoet_automation_run_logs: Δεδομένα: 0.02MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
wp_mailpoet_automation_run_subjects: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_mailpoet_automation_triggers: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_mailpoet_automation_versions: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_mailpoet_custom_fields: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_mailpoet_dynamic_segment_filters: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_mailpoet_feature_flags: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_mailpoet_forms: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_mailpoet_log: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_mailpoet_migrations: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_mailpoet_newsletters: Δεδομένα: 0.02MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
wp_mailpoet_newsletter_links: Δεδομένα: 0.02MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
wp_mailpoet_newsletter_option: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_mailpoet_newsletter_option_fields: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_mailpoet_newsletter_posts: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_mailpoet_newsletter_segment: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_mailpoet_newsletter_templates: Δεδομένα: 2.52MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_mailpoet_scheduled_tasks: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_mailpoet_scheduled_task_subscribers: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_mailpoet_segments: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_mailpoet_sending_queues: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_mailpoet_settings: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_mailpoet_statistics_bounces: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_mailpoet_statistics_clicks: Δεδομένα: 0.02MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
wp_mailpoet_statistics_forms: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_mailpoet_statistics_newsletters: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_mailpoet_statistics_opens: Δεδομένα: 0.02MB + Ευρετήρια: 0.08MB + Μηχανή InnoDB.
wp_mailpoet_statistics_unsubscribes: Δεδομένα: 0.02MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
wp_mailpoet_statistics_woocommerce_purchases: Δεδομένα: 0.02MB + Ευρετήρια: 0.08MB + Μηχανή InnoDB.
wp_mailpoet_stats_notifications: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_mailpoet_subscribers: Δεδομένα: 0.02MB + Ευρετήρια: 0.23MB + Μηχανή InnoDB.
wp_mailpoet_subscriber_custom_field: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_mailpoet_subscriber_ips: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_mailpoet_subscriber_segment: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_mailpoet_subscriber_tag: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_mailpoet_tags: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_mailpoet_user_agents: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_mailpoet_user_flags: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_options: Δεδομένα: 30.47MB + Ευρετήρια: 0.09MB + Μηχανή InnoDB.
wp_postmeta: Δεδομένα: 6.19MB + Ευρετήρια: 0.23MB + Μηχανή InnoDB.
wp_posts: Δεδομένα: 1.20MB + Ευρετήρια: 0.13MB + Μηχανή InnoDB.
wp_seopress_content_analysis: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_snippets: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_termmeta: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_terms: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_term_relationships: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_term_taxonomy: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_usermeta: Δεδομένα: 0.09MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_users: Δεδομένα: 0.02MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
wp_wcpdf_invoice_number: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_wc_admin_notes: Δεδομένα: 0.06MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_wc_admin_note_actions: Δεδομένα: 0.05MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_wc_category_lookup: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_wc_customer_lookup: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_wc_download_log: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_wc_orders: Δεδομένα: 0.02MB + Ευρετήρια: 0.11MB + Μηχανή InnoDB.
wp_wc_orders_meta: Δεδομένα: 0.06MB + Ευρετήρια: 0.09MB + Μηχανή InnoDB.
wp_wc_order_addresses: Δεδομένα: 0.02MB + Ευρετήρια: 0.06MB + Μηχανή InnoDB.
wp_wc_order_coupon_lookup: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_wc_order_operational_data: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_wc_order_product_lookup: Δεδομένα: 0.02MB + Ευρετήρια: 0.06MB + Μηχανή InnoDB.
wp_wc_order_stats: Δεδομένα: 0.02MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
wp_wc_order_tax_lookup: Δεδομένα: 0.02MB + Ευρετήρια: 0.03MB + Μηχανή InnoDB.
wp_wc_product_attributes_lookup: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_wc_product_download_directories: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_wc_product_meta_lookup: Δεδομένα: 0.02MB + Ευρετήρια: 0.09MB + Μηχανή InnoDB.
wp_wc_rate_limits: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_wc_reserved_stock: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_wc_tax_rate_classes: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_wc_webhooks: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_wpforms_entries: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_wpforms_entry_fields: Δεδομένα: 0.02MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
wp_wpforms_entry_meta: Δεδομένα: 0.02MB + Ευρετήρια: 0.02MB + Μηχανή InnoDB.
wp_wpforms_logs: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.
wp_wpforms_payments: Δεδομένα: 0.02MB + Ευρετήρια: 0.14MB + Μηχανή InnoDB.
wp_wpforms_payment_meta: Δεδομένα: 0.02MB + Ευρετήρια: 0.05MB + Μηχανή InnoDB.
wp_wpforms_tasks_meta: Δεδομένα: 0.02MB + Ευρετήρια: 0.00MB + Μηχανή InnoDB.

### Post Type Counts ###

acf-field: 5
acf-field-group: 1
attachment: 729
custom_css: 1
customize_changeset: 72
draseis: 9
e-landing-page: 1
elementor_library: 16
give_forms: 4
give_payment: 4
home-slides: 2
mailpoet_page: 1
nav_menu_item: 15
page: 22
post: 8
product: 1
revision: 191
shop_order_placehold: 25
wp_global_styles: 3
wp_navigation: 1
wpforms: 2

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (22) ###

Advanced Custom Fields: από τον/την WP Engine – 6.2.9
Astra Pro: από τον/την Brainstorm Force – 4.6.5
Classic Editor: από τον/την Συντελεστές WordPress – 1.6.3
Code Snippets: από τον/την Code Snippets Pro – 3.6.4
CookieYes | GDPR Cookie Consent: από τον/την CookieYes – 3.2.2
Custom Post Type UI: από τον/την WebDevStudios – 1.16.0
Elementor Pro: από τον/την Elementor.com – 3.21.0
Elementor: από τον/την Elementor.com – 3.21.1
Essential Addons for Elementor: από τον/την WPDeveloper – 5.9.15
Image Optimizer by Elementor – Compress, Resize and Optimize Images: από τον/την Elementor.com – 1.3.0
Jetpack: από τον/την Automattic. – 13.3.1
Loco Translate: από τον/την Tim Whitlock – 2.6.7
MailPoet: από τον/την MailPoet – 4.48.2
UpdraftPlus - Backup/Restore: από τον/την UpdraftPlus.Com
DavidAnderson – 1.24.2

Donation Platform for WooCommerce: Fundraising & Donation Management: από τον/την Jonas Höbenreich – 1.3.1
Checkout Field Editor for WooCommerce: από τον/την ThemeHigh – 2.0.1
WooCommerce JCCGateway Checkout plugin: από τον/την JCCGateway – 5.0.0
WooPayments: από τον/την Automattic – 7.5.1
PDF Invoices & Packing Slips for WooCommerce: από τον/την WP Overnight – 3.8.0
WooCommerce: από τον/την Automattic – 8.8.2
SEOPress: από τον/την The SEO Guys at SEOPress – 7.6.1
WPForms: από τον/την WPForms – 1.8.7.2

### Dropin Plugins () ###

object-cache.php: Redis Object Cache Drop-In

### Must Use Plugins (1) ###

EasyWP Plugin: από τον/την Namecheap
Inc. – 1.1.1

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: left_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature screen enabled: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 ημέρες
Level threshold: –
Log directory size: 959 B

### WC Pages ###

Βάση καταστήματος: #46 - /shop/
Καλάθι: #47 - /cart/
Ταμείο: #48 - /checkout/
Ο λογαριασμός μου: ❌ Η σελίδα δεν περιέχει το shortcode [woocommerce_my_account].
Όροι και Προϋποθέσεις: ❌ Η σελίδα δεν ορίστηκε

### Theme ###

Name: IHA Cyprus
Version: 1.0.0
Author URL: http://wpastra.com/about/
Child Theme: ✔
Parent Theme Name: Astra
Parent Theme Version: 4.6.9 – Η έκδοση 4.6.12 είναι διαθέσιμη
Parent Theme Author URL: https://wpastra.com/about/?utm_source=theme_preview&utm_medium=author_link&utm_campaign=astra_theme
WooCommerce Support: ✔

### Templates ###

Overrides: astra-child/woocommerce/emails/admin-failed-order.php
astra-child/woocommerce/emails/admin-new-order.php

### WooPayments ###

Version: 7.5.1
Connected to WPCOM: ❌ No
Logging: Disabled

### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
product-custom-fields
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-04-19 12:27:44 +03:00
Options: ✔
Notes: 77
Onboarding: completed

### MailPoet ###

Sending Method: MailPoet
Send all site's emails with: Προεπιλεγμένη μέθοδος αποστολής WordPress
Task Scheduler method: Action Scheduler
Cron ping URL: https://ihacyprus.org?mailpoet_router&endpoint=cron_daemon&action=ping

### Action Scheduler ###

Ολοκληρωμένη: 389
Oldest: 2024-03-19 16:33:37 +0200
Newest: 2024-04-19 14:25:00 +0300

Αποτυχία: 1.939
Oldest: 2024-02-29 20:54:52 +0200
Newest: 2024-04-16 15:49:16 +0300

Σε αναμονή: 14
Oldest: 2024-04-19 14:27:00 +0300
Newest: 2024-04-26 13:07:20 +0300

### Status report information ###

Generated at: 2024-04-19 14:26:21 +03:00
`

**Comment by jonas-hoebenreich** [comment]
If the issue occurs even when you have compatibility mode enabled I'm pretty sure the bug is not caused by Donation Platform for WooCommerce. Can you please check if the issue still persists when you deactivate the plugin?
