### ISSUE TITLE
what is the use of attributes param in url ?

### ISSUE THREAD

**Issue by procontentxyz** [jonas-hoebenreich/wc-donation-platform#8]
what is the use of "attribute_xxx - Specify the value of custom attributes" in url parameters,

How could we use it?

can we pass custom attribute to any order checkout...??

please share a use case example... it will help understand its need??

**Comment by jonas-hoebenreich** [comment]
Please excuse that the documentation is not so detailed. The attributes only apply to variable products. When you create a variable product, it has different attributes, e.g. donation frequency. In this example you can see how these are passed:
https://wcdp.jonh.eu/checkout/?postid=4390&donation-amount=200&wcdp-donation-amount=200&donation-frequency=monthly&attribute_donation-frequency=monthly
